"use client"

// ProductMasterFormDialog — create + edit. product_code is auto-generated by the backend
// (CST + type_code + YYMM + seq), so it's NEVER an editable input.
import { useEffect } from "react"
import { Loader2 } from "lucide-react"
import { useForm } from "react-hook-form"
import { z } from "zod"
import { zodResolver } from "@hookform/resolvers/zod"

import { Button } from "@/components/ui/button"
import {
  Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle,
} from "@/components/ui/dialog"
import { Form, FormControl, FormDescription, FormField, FormItem, FormLabel, FormMessage } from "@/components/ui/form"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { ProductTypeCombobox } from "@/components/finance/comboboxes"
import { useCreateCostProductMaster, useUpdateCostProductMaster } from "@/hooks/finance/use-cost-product-master"
import type { CostProductMaster } from "@/types/finance/cost-product-master"

const schema = z.object({
  productTypeId: z.number().int().positive("Pick a product type"),
  productName: z.string().min(1, "Required").max(500, "Max 500 chars"),
  shadeCode: z.string().max(50, "Max 50 chars"),
  gradeCode: z.string().max(20, "Max 20 chars"),
  description: z.string().max(2000, "Max 2000 chars"),
})

type FormValues = z.infer<typeof schema>

interface Props {
  open: boolean
  onOpenChange: (open: boolean) => void
  product?: CostProductMaster | null
}

export function ProductMasterFormDialog({ open, onOpenChange, product }: Props) {
  const isEditing = !!product
  const createMutation = useCreateCostProductMaster()
  const updateMutation = useUpdateCostProductMaster()

  const form = useForm<FormValues>({
    resolver: zodResolver(schema) as never,
    defaultValues: {
      productTypeId: 0, productName: "", shadeCode: "", gradeCode: "AX", description: "",
    },
  })

  useEffect(() => {
    if (open) {
      form.reset({
        productTypeId: product?.productTypeId ?? 0,
        productName: product?.productName ?? "",
        shadeCode: product?.shadeCode ?? "",
        gradeCode: product?.gradeCode || "AX",
        description: product?.description ?? "",
      })
    }
  }, [open, product, form])

  async function onSubmit(values: FormValues) {
    try {
      if (isEditing && product) {
        await updateMutation.mutateAsync({
          productSysId: product.productSysId,
          productName: values.productName,
          shadeCode: values.shadeCode,
          gradeCode: values.gradeCode,
          description: values.description,
        })
      } else {
        await createMutation.mutateAsync({
          productTypeId: values.productTypeId,
          productName: values.productName,
          shadeCode: values.shadeCode,
          gradeCode: values.gradeCode,
          description: values.description,
        })
      }
      onOpenChange(false)
    } catch {
      // toast already shown by hook
    }
  }

  const submitting = createMutation.isPending || updateMutation.isPending

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-xl">
        <DialogHeader>
          <DialogTitle>{isEditing ? "Edit product" : "New product"}</DialogTitle>
          <DialogDescription>
            {isEditing
              ? `Editing ${product?.productCode}. Product code and type are immutable.`
              : "Product code will be auto-generated as CST + type_code + YYMM + 6-digit sequence."}
          </DialogDescription>
        </DialogHeader>
        <Form {...form}>
          <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-4">
            {!isEditing && (
              <FormField
                control={form.control}
                name="productTypeId"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Product type *</FormLabel>
                    <FormControl>
                      <ProductTypeCombobox
                        value={field.value || undefined}
                        onChange={(typeId) => field.onChange(typeId)}
                      />
                    </FormControl>
                    <FormDescription>The product code prefix derives from the selected type.</FormDescription>
                    <FormMessage />
                  </FormItem>
                )}
              />
            )}
            <FormField
              control={form.control}
              name="productName"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Product name *</FormLabel>
                  <FormControl>
                    <Input {...field} placeholder="Example: POY 75/72 SD BRIGHT" />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
            <div className="grid grid-cols-2 gap-4 items-start">
              <FormField
                control={form.control}
                name="shadeCode"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Shade</FormLabel>
                    <FormControl>
                      <Input {...field} placeholder="NL / Z114S / …" />
                    </FormControl>
                    <FormDescription>Optional master shade reference.</FormDescription>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="gradeCode"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Grade</FormLabel>
                    <FormControl>
                      <Input {...field} placeholder="AX" />
                    </FormControl>
                    <FormDescription>Default AX.</FormDescription>
                    <FormMessage />
                  </FormItem>
                )}
              />
            </div>
            <FormField
              control={form.control}
              name="description"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Description</FormLabel>
                  <FormControl>
                    <Textarea {...field} rows={3} />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
            <DialogFooter>
              <Button type="button" variant="outline" onClick={() => onOpenChange(false)}>
                Cancel
              </Button>
              <Button type="submit" disabled={submitting}>
                {submitting && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
                {isEditing ? "Save changes" : "Create"}
              </Button>
            </DialogFooter>
          </form>
        </Form>
      </DialogContent>
    </Dialog>
  )
}
