"use client"

// ProductMasterFormDialog — create + edit. product_code is auto-generated by the backend
// (CST + type_code + YYMM + seq), so it's NEVER an editable input.
import { useEffect } from "react"
import { Loader2 } from "lucide-react"
import { useForm } from "react-hook-form"
import { z } from "zod"
import { zodResolver } from "@hookform/resolvers/zod"

import { Button } from "@/components/ui/button"
import {
  Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle,
} from "@/components/ui/dialog"
import { Form, FormControl, FormDescription, FormField, FormItem, FormLabel, FormMessage } from "@/components/ui/form"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { ProductTypeCombobox } from "@/components/finance/comboboxes"
import { useCreateCostProductMaster, useUpdateCostProductMaster } from "@/hooks/finance/use-cost-product-master"
import type { CostProductMaster } from "@/types/finance/cost-product-master"

const schema = z.object({
  productTypeId: z.number().int().positive("Pick a product type"),
  productName: z.string().min(1, "Required").max(500, "Max 500 chars"),
  shadeCode: z.string().max(50, "Max 50 chars"),
  gradeCode: z.string().max(20, "Max 20 chars"),
  description: z.string().max(2000, "Max 2000 chars"),
  flex01: z.string().max(255, "Max 255 chars"),
  flex02: z.string().max(100, "Max 100 chars"),
  flex03: z.string().max(100, "Max 100 chars"),
  erpFgType: z.string().max(15, "Max 15 chars").optional(),
  erpChpItemCode: z.string().max(50, "Max 50 chars").optional(),
  erpMsBatchItem: z.string().max(12, "Max 12 chars").optional(),
  erpItemType: z.string().max(20, "Max 20 chars").optional(),
  erpPrdPerDay: z.string().regex(/^$|^\d{1,15}(\.\d{1,5})?$/, "Up to 15 digits, max 5 decimals").optional(),
})

type FormValues = z.infer<typeof schema>

interface Props {
  open: boolean
  onOpenChange: (open: boolean) => void
  product?: CostProductMaster | null
  /** Called after a successful create/update, before the dialog closes. */
  onSuccess?: () => void
}

export function ProductMasterFormDialog({ open, onOpenChange, product, onSuccess }: Props) {
  const isEditing = !!product
  const createMutation = useCreateCostProductMaster()
  const updateMutation = useUpdateCostProductMaster()

  const form = useForm<FormValues>({
    resolver: zodResolver(schema) as never,
    defaultValues: {
      productTypeId: 0, productName: "", shadeCode: "", gradeCode: "AX", description: "",
      flex01: "", flex02: "", flex03: "",
      erpFgType: "", erpChpItemCode: "", erpMsBatchItem: "", erpItemType: "", erpPrdPerDay: "",
    },
  })

  useEffect(() => {
    if (open) {
      form.reset({
        productTypeId: product?.productTypeId ?? 0,
        productName: product?.productName ?? "",
        shadeCode: product?.shadeCode ?? "",
        gradeCode: product?.gradeCode || "AX",
        description: product?.description ?? "",
        flex01: product?.flex01 ?? "",
        flex02: product?.flex02 ?? "",
        flex03: product?.flex03 ?? "",
        erpFgType: product?.erpFgType ?? "",
        erpChpItemCode: product?.erpChpItemCode ?? "",
        erpMsBatchItem: product?.erpMsBatchItem ?? "",
        erpItemType: product?.erpItemType ?? "",
        erpPrdPerDay: product?.erpPrdPerDay ?? "",
      })
    }
  }, [open, product, form])

  async function onSubmit(values: FormValues) {
    try {
      if (isEditing && product) {
        await updateMutation.mutateAsync({
          productSysId: product.productSysId,
          productName: values.productName,
          shadeCode: values.shadeCode,
          gradeCode: values.gradeCode,
          description: values.description,
          flex01: values.flex01,
          flex02: values.flex02,
          flex03: values.flex03,
          erpFgType: values.erpFgType,
          erpChpItemCode: values.erpChpItemCode,
          erpMsBatchItem: values.erpMsBatchItem,
          erpItemType: values.erpItemType,
          erpPrdPerDay: values.erpPrdPerDay,
        })
      } else {
        await createMutation.mutateAsync({
          productTypeId: values.productTypeId,
          productName: values.productName,
          shadeCode: values.shadeCode,
          gradeCode: values.gradeCode,
          description: values.description,
          flex01: values.flex01,
          flex02: values.flex02,
          flex03: values.flex03,
          erpFgType: values.erpFgType,
          erpChpItemCode: values.erpChpItemCode,
          erpMsBatchItem: values.erpMsBatchItem,
          erpItemType: values.erpItemType,
          erpPrdPerDay: values.erpPrdPerDay,
        })
      }
      onSuccess?.()
      onOpenChange(false)
    } catch {
      // toast already shown by hook
    }
  }

  const submitting = createMutation.isPending || updateMutation.isPending

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-xl">
        <DialogHeader>
          <DialogTitle>{isEditing ? "Edit product" : "New product"}</DialogTitle>
          <DialogDescription>
            {isEditing
              ? `Editing ${product?.productCode}. Product code and type are immutable.`
              : "Product code will be auto-generated as CST + type_code + YYMM + 6-digit sequence."}
          </DialogDescription>
        </DialogHeader>
        <Form {...form}>
          <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-4">
            {!isEditing && (
              <FormField
                control={form.control}
                name="productTypeId"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Product type *</FormLabel>
                    <FormControl>
                      <ProductTypeCombobox
                        value={field.value || undefined}
                        onChange={(typeId) => field.onChange(typeId)}
                        // Guard E2: MB products are never created by hand — they
                        // are born from an MB Recipe only.
                        excludeTypeCodes={["MB"]}
                      />
                    </FormControl>
                    <FormDescription>The product code prefix derives from the selected type.</FormDescription>
                    <FormMessage />
                  </FormItem>
                )}
              />
            )}
            <FormField
              control={form.control}
              name="productName"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Product name *</FormLabel>
                  <FormControl>
                    <Input {...field} placeholder="Example: POY 75/72 SD BRIGHT" />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
            <div className="grid grid-cols-2 gap-4 items-start">
              <FormField
                control={form.control}
                name="shadeCode"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Shade</FormLabel>
                    <FormControl>
                      <Input {...field} placeholder="NL / Z114S / …" />
                    </FormControl>
                    <FormDescription>Optional master shade reference. MB SP Code & Dye will be filled automatically from this shade (if found in MB Spin or Superba Cost SP).</FormDescription>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="gradeCode"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Grade</FormLabel>
                    <FormControl>
                      <Input {...field} placeholder="AX" />
                    </FormControl>
                    <FormDescription>Default AX.</FormDescription>
                    <FormMessage />
                  </FormItem>
                )}
              />
            </div>
            <FormField
              control={form.control}
              name="description"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Description</FormLabel>
                  <FormControl>
                    <Textarea {...field} rows={3} />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
            <details className="rounded border p-3 text-sm">
              <summary className="cursor-pointer select-none font-medium text-muted-foreground">
                Legacy / Import identifiers (optional)
              </summary>
              <div className="mt-3 space-y-3">
                <FormField
                  control={form.control}
                  name="flex02"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Oracle Sys ID</FormLabel>
                      <FormControl>
                        <Input {...field} placeholder="e.g. 2512" />
                      </FormControl>
                      <FormDescription>Legacy Oracle integer sys_id (legacy_oracle_sys_id).</FormDescription>
                      <FormMessage />
                    </FormItem>
                  )}
                />
                <FormField
                  control={form.control}
                  name="flex01"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>ERP Compound Key</FormLabel>
                      <FormControl>
                        <Input {...field} placeholder="e.g. INV.FG.001" />
                      </FormControl>
                      <FormDescription>Legacy ERP compound key (legacy_erp_compound_key).</FormDescription>
                      <FormMessage />
                    </FormItem>
                  )}
                />
                <FormField
                  control={form.control}
                  name="flex03"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Type Label</FormLabel>
                      <FormControl>
                        <Input {...field} placeholder="e.g. FINISH" />
                      </FormControl>
                      <FormDescription>Legacy product type label (legacy_type_label).</FormDescription>
                      <FormMessage />
                    </FormItem>
                  )}
                />
              </div>
            </details>
            <details className="rounded border p-3 text-sm">
              <summary className="cursor-pointer select-none font-medium text-muted-foreground">
                ERP attributes (optional)
              </summary>
              <div className="mt-3 space-y-3">
                {isEditing && (
                  <div className="space-y-1">
                    <p className="text-xs text-muted-foreground">ERP item code</p>
                    <p className="font-mono text-sm">{product?.erpItemCode || "-"}</p>
                    <p className="text-xs text-muted-foreground">Linked via ERP Integration (item + product shade)</p>
                  </div>
                )}
                <FormField
                  control={form.control}
                  name="erpFgType"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>FG Type</FormLabel>
                      <FormControl>
                        <Input {...field} value={field.value ?? ""} />
                      </FormControl>
                      <FormDescription>Max 15.</FormDescription>
                      <FormMessage />
                    </FormItem>
                  )}
                />
                <FormField
                  control={form.control}
                  name="erpChpItemCode"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>CHP Item Code</FormLabel>
                      <FormControl>
                        <Input {...field} value={field.value ?? ""} />
                      </FormControl>
                      <FormDescription>Max 50.</FormDescription>
                      <FormMessage />
                    </FormItem>
                  )}
                />
                <FormField
                  control={form.control}
                  name="erpMsBatchItem"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>MS Batch Item</FormLabel>
                      <FormControl>
                        <Input {...field} value={field.value ?? ""} />
                      </FormControl>
                      <FormDescription>Max 12.</FormDescription>
                      <FormMessage />
                    </FormItem>
                  )}
                />
                <FormField
                  control={form.control}
                  name="erpItemType"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Item Type</FormLabel>
                      <FormControl>
                        <Input {...field} value={field.value ?? ""} />
                      </FormControl>
                      <FormDescription>Max 20.</FormDescription>
                      <FormMessage />
                    </FormItem>
                  )}
                />
                <FormField
                  control={form.control}
                  name="erpPrdPerDay"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Production per day</FormLabel>
                      <FormControl>
                        <Input {...field} value={field.value ?? ""} />
                      </FormControl>
                      <FormDescription>Decimal, max 5 decimals.</FormDescription>
                      <FormMessage />
                    </FormItem>
                  )}
                />
              </div>
            </details>
            <DialogFooter>
              <Button type="button" variant="outline" onClick={() => onOpenChange(false)}>
                Cancel
              </Button>
              <Button type="submit" disabled={submitting}>
                {submitting && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
                {isEditing ? "Save changes" : "Create"}
              </Button>
            </DialogFooter>
          </form>
        </Form>
      </DialogContent>
    </Dialog>
  )
}
