// IAM Types barrel export
// Note: Both user.ts and role.ts export ACTIVE_FILTER_OPTIONS and ActiveFilter,
// so we need explicit re-exports to avoid ambiguity.

// User types
export {
  ActiveFilter,
  activeFilterFromJSON,
  activeFilterToJSON,
  ACTIVE_FILTER_LABELS,
  ACTIVE_FILTER_OPTIONS,
} from "./user"

export type {
  User,
  UserDetail,
  UserWithDetail,
  SectionInfo,
  CreateUserRequest,
  CreateUserResponse,
  GetUserRequest,
  GetUserResponse,
  GetUserDetailRequest,
  GetUserDetailResponse,
  UpdateUserRequest,
  UpdateUserResponse,
  UpdateUserDetailRequest,
  UpdateUserDetailResponse,
  DeleteUserRequest,
  DeleteUserResponse,
  ListUsersRequest,
  ListUsersResponse,
  AssignUserRolesRequest,
  AssignUserRolesResponse,
  RemoveUserRolesRequest,
  RemoveUserRolesResponse,
  GetUserRolesAndPermissionsRequest,
  GetUserRolesAndPermissionsResponse,
  UserAccessInfo,
  RoleWithPermissions,
  Permission,
  ListUsersParams,
  UserCreateFormData,
  UserEditFormData,
} from "./user"

export {
  UserParser,
  UserDetailParser,
  UserWithDetailParser,
  CreateUserResponseParser,
  GetUserResponseParser,
  GetUserDetailResponseParser,
  UpdateUserResponseParser,
  UpdateUserDetailResponseParser,
  DeleteUserResponseParser,
  ListUsersResponseParser,
  AssignUserRolesResponseParser,
  RemoveUserRolesResponseParser,
  GetUserRolesAndPermissionsResponseParser,
  DEFAULT_USER_FORM_VALUES,
} from "./user"

// Role & Permission types
export type {
  Role,
  CreateRoleRequest,
  CreateRoleResponse,
  GetRoleRequest,
  GetRoleResponse,
  UpdateRoleRequest,
  UpdateRoleResponse,
  DeleteRoleRequest,
  DeleteRoleResponse,
  ListRolesRequest,
  ListRolesResponse,
  AssignRolePermissionsRequest,
  AssignRolePermissionsResponse,
  RemoveRolePermissionsRequest,
  RemoveRolePermissionsResponse,
  GetRolePermissionsRequest,
  GetRolePermissionsResponse,
  PermissionDetail,
  CreatePermissionRequest,
  CreatePermissionResponse,
  GetPermissionRequest,
  GetPermissionResponse,
  UpdatePermissionRequest,
  UpdatePermissionResponse,
  DeletePermissionRequest,
  DeletePermissionResponse,
  ListPermissionsRequest,
  ListPermissionsResponse,
  GetPermissionsByServiceRequest,
  GetPermissionsByServiceResponse,
  ServicePermissions,
  ModulePermissions,
  ListRolesParams,
  ListPermissionsParams,
  RoleFormData,
} from "./role"

export {
  RoleParser,
  CreateRoleResponseParser,
  GetRoleResponseParser,
  UpdateRoleResponseParser,
  DeleteRoleResponseParser,
  ListRolesResponseParser,
  AssignRolePermissionsResponseParser,
  RemoveRolePermissionsResponseParser,
  GetRolePermissionsResponseParser,
  PermissionDetailParser,
  CreatePermissionResponseParser,
  GetPermissionResponseParser,
  UpdatePermissionResponseParser,
  DeletePermissionResponseParser,
  ListPermissionsResponseParser,
  GetPermissionsByServiceResponseParser,
  DEFAULT_ROLE_FORM_VALUES,
  ACTION_TYPE_OPTIONS,
} from "./role"
